# Site settings 
title: 'J4f3th Blog'
description: 'Blog acerca de hacking y ciberseguridad.'
keyword: 'ruby, rails, sinatra, javascript, vuejs, expressjs'
url: '' 
baseurl: ''

# Navigation links
nav:
  home: '/'
  about: '/about.html' 
  tags: '/tags.html' 
  project: '/projects.html' 

# Footer
footer:
  since: 2019

# Author 
author: 'Jafeth'
nickname: 'j4f3th'
bio: 'Soy Jafeth un amante del hacking y de la ciberseguridad, estudio hacking desde el 2020 y mi mayor  aspiración es lograr ser "OSCP".'
avatar: 'assets/img/profile.png'

# Search
search: true

# Night mode
nightMode: true #always_true

# Comments
comments:
  disqus: true
  disqus_url: 'https://rokhimin.disqus.com/embed.js'

# MathJax by Ray-Eldath
mathjax: false

# Share
social-share: false
social-share-items: ['vk', 'facebook', 'twitter']

# theme color
theme-color: 'default' 

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'assets/img/banner.jpg'

# SNS settings 
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
#  email: 'mailto:whdzera@gmail.com'
  github: '//github.com/j4f3th'
#  linkedin: '//www.linkedin.com/in/rokhim-wahid-4b4209142'
  instagram: '//www.instagram.com/j4f3th'
#  twitter: '//twitter.com/rokhiminwahid'

# Tags 
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', '_darkness', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: false

# Permalink
permalink: /:title.rb

# Plugins
plugins: [jekyll-paginate]
